### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by LastGhost01** [PixelOutlaw/MythicDrops#296]
[08:11:38] [Server thread/ERROR]: Error occurred while enabling MythicDrops v4.0.12-e31947a (Is it up to date?)
java.lang.IllegalArgumentException: Input string is NULL or empty
    at com.github.zafarkhaja.mythicdrops.semver.VersionParser.<init>(VersionParser.java:162) ~[?:?]
    at com.github.zafarkhaja.mythicdrops.semver.VersionParser.parseValidSemVer(VersionParser.java:194) ~[?:?]
    at com.github.zafarkhaja.mythicdrops.semver.Version.valueOf(Version.java:265) ~[?:?]
    at com.tealcube.minecraft.bukkit.config.VersionedSmartYamlConfiguration.needsToUpdate(VersionedSmartYamlConfiguration.java:143) ~[?:?]
    at com.tealcube.minecraft.bukkit.config.VersionedSmartYamlConfiguration.update(VersionedSmartYamlConfiguration.java:154) ~[?:?]
    at com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin.reloadConfigurationFiles(MythicDropsPlugin.java:302) ~[?:?]
    at com.tealcube.minecraft.bukkit.mythicdrops.MythicDropsPlugin.onEnable(MythicDropsPlugin.java:635) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.<init>(CraftServer.java:256) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at net.minecraft.server.v1_9_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at net.minecraft.server.v1_9_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:182) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.9.2.jar:git-Bukkit-4cb3258]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]

It is the newest version. What is wrong here?

**Comment by Nunnery** [comment]
You're missing a version field in one of your files. Check them, find the one that doesn't have a version field, check here (https://github.com/Nunnery/MythicDrops/tree/master/src/main/resources) for the correct version, and then edit the file so it has the correct version field.
