### ISSUE TITLE
This huge error when players join, its persistent and repeats every millisecond.

### ISSUE THREAD

**Issue by psyKonetix** [PixelOutlaw/MythicDrops#342]
Oh, and when trying to spawn any special items, though none of my config is invalid (i parsed it all), i get an internal error.
`[11:03:02 ERROR]: Could not pass event CreatureSpawnEvent to MythicDrops v4.1.2-bd6c06f
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:284) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1033) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1112) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.SpawnerCreature.a(SpawnerCreature.java:188) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:287) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_151]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_151]
	at java.util.Collections$UnmodifiableList.get(Unknown Source) ~[?:1.8.0_151]
	at com.tealcube.minecraft.bukkit.mythicdrops.items.MythicDropBuilder.randomVariableReplace(MythicDropBuilder.java:437) ~[?:?]
	at com.tealcube.minecraft.bukkit.mythicdrops.items.MythicDropBuilder.generateLore(MythicDropBuilder.java:424) ~[?:?]
	at com.tealcube.minecraft.bukkit.mythicdrops.items.MythicDropBuilder.build(MythicDropBuilder.java:194) ~[?:?]
	at com.tealcube.minecraft.bukkit.mythicdrops.spawning.ItemSpawningListener.onCreatureSpawnEvent(ItemSpawningListener.java:172) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	... 13 more`

**Comment by Nunnery** [comment]
Fixed this a little while ago, just haven't released the fix to the public yet. Try this build: https://artifactory.pixeloutlaw.io/artifactory/public/com/tealcube/minecraft/bukkit/mythicdrops/4.1.3-SNAPSHOT/mythicdrops-4.1.3-20171227.212955-13.jar
