### ISSUE TITLE
Vault Error on load 1.13.2

### ISSUE THREAD

**Issue by Blackyvk** [PixelOutlaw/MythicDrops#360]
Vault version 1.7.1-b91
MythicDrops version 4.3.5-SNAPSHOT-3f2afae

```
[07:38:06] [Server thread/INFO]: [MythicMobs] MythicMobs MythicDrops Support has been enabled!
[07:38:06] [Server thread/INFO]: [MythicMobs] MythicMobs Vault Support has been enabled!
[07:38:06] [Server thread/WARN]: java.lang.NullPointerException
[07:38:06] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
[07:38:06] [Server thread/WARN]: 	at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100)
[07:38:06] [Server thread/WARN]: 	at io.lumine.xikage.mythicmobs.compatibility.WorldGuardSupport.<init>(WorldGuardSupport.java:19)
[07:38:06] [Server thread/WARN]: 	at io.lumine.xikage.mythicmobs.compatibility.CompatibilityManager.lambda$new$49(CompatibilityManager.java:52)
[07:38:06] [Server thread/WARN]: 	at io.lumine.xikage.mythicmobs.compatibility.CompatibilityManager.registerCompatibility(CompatibilityManager.java:85)
[07:38:06] [Server thread/WARN]: 	at io.lumine.xikage.mythicmobs.compatibility.CompatibilityManager.<init>(CompatibilityManager.java:52)
[07:38:06] [Server thread/WARN]: 	at io.lumine.xikage.mythicmobs.MythicMobs.onEnable(MythicMobs.java:140)
[07:38:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[07:38:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[07:38:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406)
[07:38:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[07:38:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[07:38:06] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[07:38:06] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[07:38:06] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[07:38:06] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[07:38:06] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[07:38:06] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:38:06] [Server thread/INFO]: [MythicMobs] MythicMobs WorldGuard Support has been enabled!
```

**Comment by Blackyvk** [comment]
Wrong plugin sorry lol
