### ISSUE TITLE
gem spawn bug

### ISSUE THREAD

**Issue by ThePhoenix96** [PixelOutlaw/MythicDrops#417]
cant spawn a gem 

`[10:23:51] [Server thread/INFO]: AvtoSenpai issued server command: /md spawn gem
[10:23:51] [Server thread/ERROR]: [ACF] Exception in command: mythicdrops spawn gem 
[10:23:51] [Server thread/ERROR]: [ACF] java.lang.reflect.InvocationTargetException
[10:23:51] [Server thread/ERROR]: [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:23:51] [Server thread/ERROR]: [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:23:51] [Server thread/ERROR]: [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:23:51] [Server thread/ERROR]: [ACF] 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.BaseCommand.executeCommand(BaseCommand.java:576)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.BaseCommand.execute(BaseCommand.java:512)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.RootCommand.execute(RootCommand.java:99)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.BukkitRootCommand.execute(BukkitRootCommand.java:79)
[10:23:51] [Server thread/ERROR]: [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[10:23:51] [Server thread/ERROR]: [ACF] 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[10:23:51] [Server thread/ERROR]: [ACF] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:23:51] [Server thread/ERROR]: [ACF] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[10:23:51] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[10:23:51] [Server thread/ERROR]: [ACF] 	at java.lang.Thread.run(Thread.java:748)
[10:23:51] [Server thread/ERROR]: [ACF] Caused by: java.lang.IllegalAccessError: kotlin/ranges/ClosedDoubleRange
[10:23:51] [Server thread/ERROR]: [ACF] 	at kotlin.ranges.RangesKt__RangesKt.rangeTo(Ranges.kt:96)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.api.choices.WeightedChoice.choose(WeightedChoice.kt:66)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.socketing.MythicSocketGemManager.randomByWeight(MythicSocketGemManager.kt:49)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.socketing.MythicSocketGemManager.randomByWeight(MythicSocketGemManager.kt:29)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.api.managers.WeightedManager$DefaultImpls.randomByWeight(WeightedManager.kt:43)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.api.socketing.SocketGemManager$DefaultImpls.randomByWeight(SocketGemManager.kt)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.socketing.MythicSocketGemManager.randomByWeight(MythicSocketGemManager.kt:29)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.socketing.MythicSocketGemManager.randomByWeight(MythicSocketGemManager.kt:29)
[10:23:51] [Server thread/ERROR]: [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.commands.SpawnCommands$NestedSpawnCommands.spawnSocketGemCommand(SpawnCommands.kt:94)
[10:23:51] [Server thread/ERROR]: [ACF] 	... 24 more`

**Comment by ThePhoenix96** [comment]
server is running CraftBukkit version git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
