### ISSUE TITLE
/md debug error

### ISSUE THREAD

**Issue by SirKillian** [PixelOutlaw/MythicDrops#490]
Plugin version: "6.3.0-dev.60+f928384"

When using the command **/md debug** the following error occurs:

**Ingame:**
![Error](https://sirkillian.gg/i/3str7vo5culupwlo.png)

**Console:**
```
[07:53:54] [Server thread/INFO]: SirKillian issued server command: /md debug
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] Exception in command: mythicdrops debug 
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] java.lang.reflect.InvocationTargetException
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.RegisteredCommand.invoke(RegisteredCommand.java:154)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.BaseCommand.execute(BaseCommand.java:513)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.RootCommand.execute(RootCommand.java:99)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1923)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1734)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1192)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1185)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1161)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/java.lang.Thread.run(Thread.java:834)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] Caused by: java.lang.IllegalArgumentException: No JsonAdapter for interface com.tealcube.minecraft.bukkit.mythicdrops.api.settings.socketing.items.SocketExtenderOptions (with no annotations)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] for interface com.tealcube.minecraft.bukkit.mythicdrops.api.settings.socketing.items.SocketExtenderOptions socketExtender
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] for class com.tealcube.minecraft.bukkit.mythicdrops.settings.socketing.MythicSocketingItems
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] for interface com.tealcube.minecraft.bukkit.mythicdrops.api.settings.socketing.SocketingItems items
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] for class com.tealcube.minecraft.bukkit.mythicdrops.settings.MythicSocketingSettings
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] for interface com.tealcube.minecraft.bukkit.mythicdrops.api.settings.SocketingSettings socketingSettings
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] for class com.tealcube.minecraft.bukkit.mythicdrops.settings.MythicSettingsManager
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] for interface com.tealcube.minecraft.bukkit.mythicdrops.api.settings.SettingsManager
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:349)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:150)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.settings.socketing.MythicSocketingItemsJsonAdapter.<init>(MythicSocketingItemsJsonAdapter.kt:40)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.internal.Util.generatedAdapter(Util.java:547)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:60)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:138)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:98)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:72)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.moshi.MythicSettingsInterfaceJsonAdapterFactory.create(MythicSettingsInterfaceJsonAdapterFactory.kt:58)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:138)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.settings.MythicSocketingSettingsJsonAdapter.<init>(MythicSocketingSettingsJsonAdapter.kt:36)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.internal.Util.generatedAdapter(Util.java:547)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:60)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:138)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:98)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:72)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.moshi.MythicSettingsInterfaceJsonAdapterFactory.create(MythicSettingsInterfaceJsonAdapterFactory.kt:58)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:138)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.settings.MythicSettingsManagerJsonAdapter.<init>(MythicSettingsManagerJsonAdapter.kt:54)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.internal.Util.generatedAdapter(Util.java:547)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:60)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:138)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:98)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:72)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.moshi.MythicSettingsInterfaceJsonAdapterFactory.create(MythicSettingsInterfaceJsonAdapterFactory.kt:58)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:138)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:98)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:72)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.commands.DebugCommand.debugCommand(DebugCommand.kt:72)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	... 27 more
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] Caused by: java.lang.IllegalArgumentException: No JsonAdapter for interface com.tealcube.minecraft.bukkit.mythicdrops.api.settings.socketing.items.SocketExtenderOptions (with no annotations)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	at com.tealcube.minecraft.bukkit.mythicdrops.shade.moshi.Moshi.adapter(Moshi.java:148)
[07:53:54] [Server thread/ERROR]: [MythicDrops] [ACF] 	... 66 more
```

**Comment by ToppleTheNun** [comment]
This was fixed by commit bb4fad6a05db3d029c0b6372b5c8eb81aec21889.
